Repository commitizen/cz-cli, pull requests merged in 2021-11, with the labels that each got.

#860 ci(azure-pipelines.yml): change the Ubuntu VM to 'latest'
  azure-pipelines.yml
Labels: linux/osx

#862 fix(deps): update dependencies from renovatebot PRs
  package-lock.json
  package.json
  test/tools/clean.js
Labels: dependency related

#864 build(node versions): - Deprecates Node 10 and adds current LTS versions
  README.md
  jobs/build.yml
  package-lock.json
  package.json
Labels: dependency related

#878 Recreate the commitizen logo in png & svg format
  .gitignore
  jobs/build.yml
  logo/commitizen-logo-color.svg
  logo/commitizen-logo-mono.svg
  logo/generate.sh
Labels: enhancement
